/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import persistencia.ManejadorArchivos;

/**
 *
 * @author user
 */
public class interfazCrearConsolidadoGeneral extends javax.swing.JFrame {

    DefaultListModel<String> modeloLista1Nombres = new DefaultListModel<>();
    DefaultListModel<String> modeloLista1Rutas = new DefaultListModel<>();
    
    public interfazCrearConsolidadoGeneral() {
        initComponents();
        txtCarpetaArchivos.setMaximumSize(new java.awt.Dimension(299, txtCarpetaArchivos.getPreferredSize().height));
        txtCarpetaArchivos.setPreferredSize(new java.awt.Dimension(299, txtCarpetaArchivos.getPreferredSize().height));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCarpetaPrincipal = new javax.swing.JTextField();
        txtCarpetaArchivos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListConsolidado = new javax.swing.JList<>();
        btnSubir = new javax.swing.JButton();
        btnBajar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Crear Consolidado General");

        jLabel2.setText("Ingrese la carpeta principal:");

        jLabel3.setText("Ingrese la carpeta con las etapas:");

        jButton1.setText("EXAMINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXAMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(JListConsolidado);

        btnSubir.setText("SUBIR");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        btnBajar.setText("BAJAR");
        btnBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajarActionPerformed(evt);
            }
        });

        jButton5.setText("BORRAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("BORRAR TODO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("CREAR CONSOLIDADO GENERAL");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton3.setText("ACEPTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubir)
                            .addComponent(btnBajar)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(txtCarpetaArchivos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92)
                        .addComponent(txtCarpetaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCarpetaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCarpetaArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSubir)
                        .addGap(18, 18, 18)
                        .addComponent(btnBajar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajarActionPerformed
        int[] indices = JListConsolidado.getSelectedIndices();

        if (indices.length == 0 || indices[indices.length - 1] >= modeloLista1Nombres.size() - 1) return;

        for (int i = indices.length - 1; i >= 0; i--) {
            int index = indices[i];
            if (index < modeloLista1Nombres.size() - 1 && !contains(indices, index + 1)) {
                // Intercambiar en modelo visual (nombres)
                String nombre = modeloLista1Nombres.get(index);
                modeloLista1Nombres.set(index, modeloLista1Nombres.get(index + 1));
                modeloLista1Nombres.set(index + 1, nombre);

                // Intercambiar en modelo lógico (rutas)
                String ruta = modeloLista1Rutas.get(index);
                modeloLista1Rutas.set(index, modeloLista1Rutas.get(index + 1));
                modeloLista1Rutas.set(index + 1, ruta);

                indices[i]++; // Actualizar índice seleccionado
            }
        }

        JListConsolidado.setSelectedIndices(indices);
    }//GEN-LAST:event_btnBajarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManejadorArchivos.seleccionarCarpetaPrincipal();
        txtCarpetaPrincipal.setText(ManejadorArchivos.getRutaCarpetaPrincipal());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        int[] indices = JListConsolidado.getSelectedIndices();

        if (indices.length == 0 || indices[0] == 0) return;

        for (int i = 0; i < indices.length; i++) {
            int index = indices[i];
            if (index > 0 && !contains(indices, index - 1)) {
                // Intercambiar en modelo visual (nombres)
                String nombre = modeloLista1Nombres.get(index);
                modeloLista1Nombres.set(index, modeloLista1Nombres.get(index - 1));
                modeloLista1Nombres.set(index - 1, nombre);

                // Intercambiar en modelo lógico (rutas)
                String ruta = modeloLista1Rutas.get(index);
                modeloLista1Rutas.set(index, modeloLista1Rutas.get(index - 1));
                modeloLista1Rutas.set(index - 1, ruta);

                indices[i]--; // Actualizar índice seleccionado
            }
        }

        JListConsolidado.setSelectedIndices(indices);
    }//GEN-LAST:event_btnSubirActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int[] indices = JListConsolidado.getSelectedIndices();

        if (indices.length > 0) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar los archivos seleccionados de la lista?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                // Eliminar en orden inverso para evitar errores por desplazamiento
                for (int i = indices.length - 1; i >= 0; i--) {
                    int index = indices[i];

                    modeloLista1Nombres.remove(index);
                    modeloLista1Rutas.remove(index);
                    ManejadorArchivos.eliminarRuta(index); // Mantiene tu lógica existente
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona uno o más archivos para eliminar.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (modeloLista1Nombres.getSize() == 0) {
        JOptionPane.showMessageDialog(this, "La lista ya está vacía.");
        return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar todos los archivos de la lista?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Limpiar el modelo visual
            modeloLista1Nombres.clear();
            modeloLista1Rutas.clear();

            // Limpiar el modelo lógico
            ManejadorArchivos.eliminarTodasLasRutas();  // Este método deberías crearlo si no existe
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ManejadorArchivos.seleccionarCarpeta(txtCarpetaArchivos);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String nombreArchivo = "merged";

        if (nombreArchivo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre para el archivo PDF.");
            return;
        }

        // Obtener la ruta inicial desde ManejadorArchivos
        String rutaInicial = ManejadorArchivos.getRutaCarpeta();
        JFileChooser selectorCarpeta = new JFileChooser(rutaInicial != null ? new File(rutaInicial) : null);
        selectorCarpeta.setDialogTitle("Seleccione la carpeta donde desea guardar el PDF fusionado");
        selectorCarpeta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        selectorCarpeta.setAcceptAllFileFilterUsed(false);

        int seleccion = selectorCarpeta.showSaveDialog(this);

        if (seleccion != JFileChooser.APPROVE_OPTION) {
            // Usuario canceló la selección
            return;
        }

        File carpetaDestino = selectorCarpeta.getSelectedFile();

        if (!carpetaDestino.exists() || !carpetaDestino.isDirectory()) {
            JOptionPane.showMessageDialog(this, "La carpeta destino no existe o no es válida.");
            return;
        }

        // ✅ Sincronizar la lista real antes de fusionar
        ManejadorArchivos.limpiarRutasArchivos();

        for (int i = 0; i < modeloLista1Rutas.size(); i++) {
            ManejadorArchivos.agregarRutaArchivo(modeloLista1Rutas.get(i));
        }

        try {
            ManejadorArchivos.unirPDFs(nombreArchivo, carpetaDestino);
            JOptionPane.showMessageDialog(this, "Archivo PDF combinado creado correctamente.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al crear el PDF: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Asegúrate de inicializar los modelos antes de usar
        modeloLista1Nombres = new DefaultListModel<>();
        modeloLista1Rutas = new DefaultListModel<>();

        
        ManejadorArchivos.cargarArchivosOrdenNombre(ManejadorArchivos.getRutaCarpeta(), modeloLista1Nombres, modeloLista1Rutas);
        JListConsolidado.setModel(modeloLista1Nombres);
    }//GEN-LAST:event_jButton3ActionPerformed

    private boolean contains(int[] array, int value) {
        for (int i : array) {
            if (i == value) return true;
        }
        return false;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazCrearConsolidadoGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazCrearConsolidadoGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazCrearConsolidadoGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazCrearConsolidadoGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazCrearConsolidadoGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListConsolidado;
    private javax.swing.JButton btnBajar;
    private javax.swing.JButton btnSubir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCarpetaArchivos;
    private javax.swing.JTextField txtCarpetaPrincipal;
    // End of variables declaration//GEN-END:variables
}
