/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.io.File;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;
import persistencia.ManejadorArchivos;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
/**
 *
 * @author user
 */
public class Interfaz extends javax.swing.JFrame {
    String nombreExpediente;
    JComponent[] componentes;
    
    public Interfaz() {
        initComponents();
        btnCrearSubcarpetas.setEnabled(false);
        txtSeleccionaFilaAutocompletado.setEnabled(false);
        jButton2.setEnabled(false);
        txtEstadoExcelAutocompletar.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCaso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroExpediente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbSIMISGD = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCarpetaExpediente = new javax.swing.JTextField();
        btnBuscarCarpeta = new javax.swing.JButton();
        txtExcel = new javax.swing.JTextField();
        btnBuscarExcel = new javax.swing.JButton();
        txtDni = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jcbMes = new javax.swing.JComboBox<>();
        txtAnio = new javax.swing.JTextField();
        txtFilaSeleccionada = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEstadoFila = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCarpetaPrincipal = new javax.swing.JTextField();
        btnBuscarCarpetaPrincipal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSeleccionaFilaAutocompletado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtEstadoExcelAutocompletar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnCrearSubcarpetas = new javax.swing.JButton();
        jCheckBoxEstadoAutocompletado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Proyecto Carpeta Unica - Archivo Unico");

        jLabel2.setText("Caso");

        jLabel3.setText("N Expediente");

        jLabel4.setText("N Expediente SIMI o SGD");

        jcbSIMISGD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIMI", "SGD" }));

        jLabel5.setText("Apellido Paterno");

        jLabel6.setText("Apellido Materno");

        jLabel7.setText("Primer Nombre");

        jLabel8.setText("Seguno Nombre");

        jLabel9.setText("DNI, si no tiene ingresar NN");

        jLabel10.setText("Año de expediente");

        jLabel11.setText("Mes de expediente");

        jLabel12.setText("Seleccionar Carpeta");

        jLabel13.setText("Excel de trabajo");

        txtCarpetaExpediente.setColumns(15);

        btnBuscarCarpeta.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnBuscarCarpeta.setText("EXAMINAR");
        btnBuscarCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCarpetaActionPerformed(evt);
            }
        });

        txtExcel.setColumns(15);

        btnBuscarExcel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnBuscarExcel.setText("EXAMINAR");
        btnBuscarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarExcelActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setText("LIMPIAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        jLabel15.setText("¿Desde que fila quiere iniciar?");

        jLabel16.setText("Estado");

        jLabel17.setText("Seleccionar carpeta Principal");

        txtCarpetaPrincipal.setColumns(15);

        btnBuscarCarpetaPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnBuscarCarpetaPrincipal.setText("EXAMINAR");
        btnBuscarCarpetaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCarpetaPrincipalActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel14.setText("Autocompletar datos en base a excel: (Los nombres se crearan automaticamente)");

        jLabel18.setText("Seleccionar fila");

        jButton2.setText("SELECCIONAR Y COMPLETAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel19.setText("Estado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(txtSeleccionaFilaAutocompletado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoExcelAutocompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtSeleccionaFilaAutocompletado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtEstadoExcelAutocompletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnCrearSubcarpetas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCrearSubcarpetas.setText("CREAR CARPETA");
        btnCrearSubcarpetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSubcarpetasActionPerformed(evt);
            }
        });

        jCheckBoxEstadoAutocompletado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBoxEstadoAutocompletado.setText("Estoy autocompletando");
        jCheckBoxEstadoAutocompletado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEstadoAutocompletadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbSIMISGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaso)
                            .addComponent(txtNumeroExpediente)
                            .addComponent(txtApellidoPaterno)
                            .addComponent(txtApellidoMaterno)
                            .addComponent(txtPrimerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtSegundoNombre)
                            .addComponent(txtDni)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrearSubcarpetas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtEstadoFila, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                                .addComponent(txtFilaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBuscarCarpeta)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel10))
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel12))
                                            .addGap(63, 63, 63)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btnBuscarCarpetaPrincipal)
                                                .addComponent(txtCarpetaExpediente, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jcbMes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtAnio)
                                                .addComponent(txtCarpetaPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(btnBuscarExcel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jCheckBoxEstadoAutocompletado))))
                .addGap(15, 67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBoxEstadoAutocompletado))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumeroExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbSIMISGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtCarpetaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCarpetaPrincipal)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCarpetaExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCarpeta)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtFilaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtEstadoFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(btnRegistrar)
                        .addComponent(btnCrearSubcarpetas)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnBuscarCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCarpetaActionPerformed
        ManejadorArchivos.seleccionarCarpeta(txtCarpetaExpediente);
        txtCarpetaExpediente.setText(ManejadorArchivos.getRutaCarpeta());
    }//GEN-LAST:event_btnBuscarCarpetaActionPerformed

    private void btnBuscarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarExcelActionPerformed
        ManejadorArchivos.seleccionarExcel(Integer.parseInt(txtFilaSeleccionada.getText()), txtEstadoFila);
        txtExcel.setText(ManejadorArchivos.getRutaCarpetaExcel());
    }//GEN-LAST:event_btnBuscarExcelActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        nombreExpediente= txtCaso.getText().toUpperCase() + "_" + txtApellidoPaterno.getText().toUpperCase() + txtApellidoMaterno.getText().toUpperCase() + txtPrimerNombre.getText().toUpperCase() + txtSegundoNombre.getText().toUpperCase() + "_" + txtDni.getText();
        String nombreCarpeta = "EXP_" + nombreExpediente;
        
        String[] nombres = {txtCaso.getText(), txtNumeroExpediente.getText(), 
            (String) jcbSIMISGD.getSelectedItem(), txtApellidoPaterno.getText().toUpperCase(), 
            txtApellidoMaterno.getText().toUpperCase(), txtPrimerNombre.getText().toUpperCase(), 
            txtSegundoNombre.getText().toUpperCase(), txtDni.getText(), (String) jcbMes.getSelectedItem(), 
            txtAnio.getText(), nombreCarpeta, nombreExpediente};
        ManejadorArchivos.agregarFilaExcel(ManejadorArchivos.getRutaCarpetaExcel(), nombres, (Integer.parseInt(txtFilaSeleccionada.getText())-1), txtEstadoFila);
        if (ManejadorArchivos.getCondicionFila() == "vacio") {
        ManejadorArchivos.procesarCarpeta(ManejadorArchivos.getRutaCarpeta(),txtDni.getText());
        ManejadorArchivos.renombrarCarpeta(ManejadorArchivos.getRutaCarpeta(), nombreCarpeta);        
        String nuevaRutaCarpeta = new File(ManejadorArchivos.getRutaCarpeta()).getParent() + File.separator + nombreCarpeta;
        ManejadorArchivos.renombrarArchivo(nuevaRutaCarpeta, new File(nuevaRutaCarpeta).getName());

        JOptionPane.showMessageDialog(null, "Datos ingresados en: " + (ManejadorArchivos.getFilaIngresada() + 1));
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtCaso.setText("");
        txtNumeroExpediente.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtPrimerNombre.setText("");
        txtSegundoNombre.setText("");
        txtDni.setText("");
        txtAnio.setText("");
        txtCarpetaExpediente.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBuscarCarpetaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCarpetaPrincipalActionPerformed
        ManejadorArchivos.seleccionarCarpetaPrincipal();
        txtCarpetaPrincipal.setText(ManejadorArchivos.getRutaCarpetaPrincipal());
    }//GEN-LAST:event_btnBuscarCarpetaPrincipalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JComponent[] componentes = {txtCaso, txtNumeroExpediente, jcbSIMISGD, txtApellidoPaterno, txtApellidoMaterno, 
                            txtPrimerNombre, txtSegundoNombre, txtDni, txtAnio, jcbMes};
        ManejadorArchivos.seleccionarExcel(Integer.parseInt(txtSeleccionaFilaAutocompletado.getText()), txtEstadoExcelAutocompletar);
        ManejadorArchivos.autocompletarPorFilaExcel(ManejadorArchivos.getRutaCarpetaExcel(), Integer.parseInt(txtSeleccionaFilaAutocompletado.getText()), componentes);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCrearSubcarpetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSubcarpetasActionPerformed
        String[] nombres = {txtCaso.getText(), txtNumeroExpediente.getText(), 
            (String) jcbSIMISGD.getSelectedItem(), txtApellidoPaterno.getText().toUpperCase(), 
            txtApellidoMaterno.getText().toUpperCase(), txtPrimerNombre.getText().toUpperCase(), 
            txtSegundoNombre.getText().toUpperCase(), txtDni.getText(), (String) jcbMes.getSelectedItem(), 
            txtAnio.getText(), ManejadorArchivos.getNombreCarpetaObtenido(), ManejadorArchivos.getNombreExpedienteObtenido()};
        String[] nombreSubcarpetas ={"1_REC_" + txtDni.getText(), "2_IDE_" + txtDni.getText(), "3_EMI_" + txtDni.getText(), 
            "4_ARC_" + txtDni.getText(), "5_APE_" + txtDni.getText(), "6_SEG_" + txtDni.getText(),
            "7_AGR_"  + txtDni.getText(), "8_CON_" + txtDni.getText()
        };
        String nombreCarpeta = "EXP_" + txtCaso.getText() + "_" + txtApellidoPaterno.getText() + 
                txtApellidoMaterno.getText() + txtPrimerNombre.getText() + txtSegundoNombre.getText() + 
                "_" + txtDni.getText();
        ManejadorArchivos.crearCarpetaConSubcarpetas(ManejadorArchivos.getRutaCarpetaPrincipal(), nombreCarpeta, nombreSubcarpetas);
    }//GEN-LAST:event_btnCrearSubcarpetasActionPerformed

    private void jCheckBoxEstadoAutocompletadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEstadoAutocompletadoActionPerformed
        boolean seleccionado = jCheckBoxEstadoAutocompletado.isSelected();
        txtFilaSeleccionada.setEnabled(!seleccionado);  // Desactiva el JTextField
        txtExcel.setEnabled(!seleccionado);  // Desactiva el JTextField
        txtEstadoFila.setEnabled(!seleccionado);  // Desactiva el JTextField
        btnBuscarExcel.setEnabled(!seleccionado);  // Desactiva el JButton
        btnRegistrar.setEnabled(!seleccionado);
        txtCarpetaExpediente.setEnabled(!seleccionado);
        btnBuscarCarpeta.setEnabled(!seleccionado);
        btnCrearSubcarpetas.setEnabled(seleccionado);
        txtSeleccionaFilaAutocompletado.setEnabled(seleccionado);
        jButton2.setEnabled(seleccionado);
        txtEstadoExcelAutocompletar.setEnabled(seleccionado);
    }//GEN-LAST:event_jCheckBoxEstadoAutocompletadoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCarpeta;
    private javax.swing.JButton btnBuscarCarpetaPrincipal;
    private javax.swing.JButton btnBuscarExcel;
    private javax.swing.JButton btnCrearSubcarpetas;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBoxEstadoAutocompletado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JComboBox<String> jcbSIMISGD;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCarpetaExpediente;
    private javax.swing.JTextField txtCarpetaPrincipal;
    private javax.swing.JTextField txtCaso;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEstadoExcelAutocompletar;
    private javax.swing.JTextField txtEstadoFila;
    private javax.swing.JTextField txtExcel;
    private javax.swing.JTextField txtFilaSeleccionada;
    private javax.swing.JTextField txtNumeroExpediente;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtSeleccionaFilaAutocompletado;
    // End of variables declaration//GEN-END:variables
}
